ClickuUpIntegration/Models/TimeDoctor/AuthenticateResult.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class AuthenticateResultModel
    {
        [JsonProperty("data")]
        public TokenResult Data { get; set; }
    }

    public class TokenResult
    {
        [JsonProperty("id")]
        public string UserId { get; set; }

        [JsonProperty("name")]
        public string UserName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("token")]
        public string Token { get; set; }
        [JsonProperty("expiresAt")]
        public string ExpireAt { get; set; }

        [JsonProperty("companies")]
        public List<Company> Companies { get; set; }
    }

    public class Company
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }
}

ClickuUpIntegration/Models/TimeDoctor/TimeDoctorEnums.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class TimeDoctorEnums
    {
        public enum GroupByTypeEnum
        {
            [Description("Group By Task")]
            GroupByTask,
            [Description("Group By User")]
            GroupByUser,
            [Description("Group By Task and User")]
            GroupByTaskAndUser
        }

        public static string GetEnumDescription(Enum value)
        {
            // Get the Description attribute value for the enum value
            FieldInfo fi = value.GetType().GetField(value.ToString());
            DescriptionAttribute[] attributes = (DescriptionAttribute[])fi.GetCustomAttributes(typeof(DescriptionAttribute), false);

            if (attributes.Length > 0)
                return attributes[0].Description;
            else
                return value.ToString();
        }
    }
}

ClickuUpIntegration/Models/TimeDoctor/TimeDoctorUsers.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class TimeDoctorUsers
    {
        [JsonProperty("data")]
        public List<Users> Users { get; set; }
    }

    public class Users
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }
    }

    public class TimeDoctorProjects
    {
        [JsonProperty("data")]
        public List<Project> Projects { get; set; }
    }
    public class Project
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }
}

ClickuUpIntegration/Models/TimeDoctor/WorkLog.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class TimeDoctorWorkLog
    {
        public TimeDoctorWorkLog()
        {
            WorkLog = new List<List<WorkLog>>();
        }
        [JsonProperty("data")]
        public List<List<WorkLog>> WorkLog { get; set; }
    }

    public class WorkLog
    {
        [JsonProperty("taskId")]
        public string TaskId { get; set; }

        [JsonProperty("projectId")]
        public string ProjectId { get; set; }

        [JsonProperty("mode")]
        public string Mode { get; set; }

        [JsonProperty("date")]
        public DateTime? Date { get; set; }

        [JsonProperty("start")]
        public DateTime? Start { get; set; }

        [JsonProperty("time")]
        public double Time { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }

        [JsonProperty("taskName")]
        public string TaskName { get; set; }

        [JsonProperty("projectName")]
        public string ProjectName { get; set; }

        [JsonProperty("deviceId")]
        public string DeviceId { get; set; }

        public string UserName { get; set; }
        public string TotalTimeSpent { get; set; }
    }

    public class ProjectTask
    {
        public string ProjectName { get; set; }
        public string ProjectId { get; set; }
        public string TaskName { get; set; }
        public string TaskId { get; set; }
        public string TotalHour { get; set; }
        public int Order { get; set; }

        public double TotalTimeSpentInProject { get; set; }

        public string UserId { get; set; }
        public string UserName { get; set; }
    }
}

ClickuUpIntegration/Models/TimeDoctor/WorkLogByUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class WorkLogByUser
    {
        public WorkLogByUser()
        {
            UserData = new List<ProjectTask>();
        }
        public string UserName { get; set; }
        public int GroupByType { get; set; }
        public string TotalUserTime { get; set; }
        public List<ProjectTask> UserData { get; set; }
    }
}

ClickuUpIntegration/Models/TimeDoctor/WorkLogFilterDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickUpIntegration.Models.TimeDoctor
{
    public class WorkLogFilterDto
    {
        public string From { get; set; }
        public string To { get; set; }
        public string UserId { get; set; }
        public string ProjectName { get; set; }
        public string CompanyId { get; set; }
        public int GroupByType { get; set; }
    }
}

ClickuUpIntegration/Controllers/TimeDoctorController.cs
using ClickUpIntegration.Helpers;
using ClickUpIntegration.Models.TimeDoctor;
using ClickUpIntegration.Settings;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static ClickUpIntegration.Models.TimeDoctor.TimeDoctorEnums;

namespace ClickUpIntegration.Controllers
{
    public class TimeDoctorController : Controller
    {
        private readonly string _baseUrl;
        private readonly IHttpContextAccessor _httpAccessor;
        public TimeDoctorController(IOptions<TimeDoctorApiSettings> timeDoctorApiSettings,
                                    IHttpContextAccessor httpAccessor)
        {
            _baseUrl = timeDoctorApiSettings.Value.EndPoint;
            _httpAccessor = httpAccessor;
        }


        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Authenticate(string username = "", string password = "")
        {
            var route = "authorization/login";
            Response<AuthenticateResultModel> response = await DataHelper<AuthenticateResultModel>.Execute(_baseUrl, route, OperationType.POST, new
            {
                email = username,
                password = password
            });

            if (response.Success)
            {
                _httpAccessor.HttpContext.Response.Cookies.Append("timedoctor_accesstoken", response.Result.Data.Token, new CookieOptions
                {
                    Expires = DateTime.Parse(response.Result.Data.ExpireAt)
                });

                _httpAccessor.HttpContext.Response.Cookies.Append("UserId", response.Result.Data.UserId, new CookieOptions
                {
                    Expires = DateTime.Parse(response.Result.Data.ExpireAt)
                });

                var companiesAsString = JsonConvert.SerializeObject(response.Result.Data.Companies);

                _httpAccessor.HttpContext.Response.Cookies.Append("Companies", companiesAsString, new CookieOptions
                {
                    Expires = DateTime.Parse(response.Result.Data.ExpireAt)
                });

                var company = response.Result.Data.Companies.FirstOrDefault(s => s.Name == "BladePorts");
                if (company != null)
                {
                    _httpAccessor.HttpContext.Response.Cookies.Append("CompanyId", company.Id, new CookieOptions
                    {
                        Expires = DateTime.Parse(response.Result.Data.ExpireAt)
                    });
                }
            }
            return Json(response);
        }

        public async Task<List<Users>> GetUserListByCompany(string companyId)
        {
            var token = _httpAccessor.HttpContext.Request.Cookies["timedoctor_accesstoken"];

            var route = $"users?company={companyId}&token={token}";
            Response<TimeDoctorUsers> response = await DataHelper<TimeDoctorUsers>.Execute(_baseUrl, route, OperationType.GET);

            return response.Result.Users;
        }

        public async Task<List<Project>> GetProjectListByCompany(string companyId)
        {
            var token = _httpAccessor.HttpContext.Request.Cookies["timedoctor_accesstoken"];
            var route = $"projects?company={companyId}&token={token}&all=true&show-integration=true";
            Response<TimeDoctorProjects> response = await DataHelper<TimeDoctorProjects>.Execute(_baseUrl, route, OperationType.GET);
            return response.Result.Projects;
        }

        public async Task<IActionResult> Users()
        {
            var token = _httpAccessor.HttpContext.Request.Cookies["timedoctor_accesstoken"];
            var companyId = _httpAccessor.HttpContext.Request.Cookies["CompanyId"];

            var route = $"users?company={companyId}&token={token}";
            Response<TimeDoctorUsers> response = await DataHelper<TimeDoctorUsers>.Execute(_baseUrl, route, OperationType.GET);

            return Json(response);
        }

        public IActionResult WorkLog()
        {
            ViewBag.Companies = JsonConvert.DeserializeObject<List<Company>>(_httpAccessor.HttpContext.Request.Cookies["Companies"]);
            ViewBag.GroupByTypes = GetGroupByType();
            return View();
        }

        private List<SelectListItem> GetGroupByType()
        {
            var groupByType = Enum.GetValues(typeof(GroupByTypeEnum)).Cast<GroupByTypeEnum>()
                     .Select(x => new SelectListItem { Text = TimeDoctorEnums.GetEnumDescription(x), Value = ((int)x).ToString() }).ToList();

            return groupByType;
        }

        public async Task<IActionResult> GetDropdowns(string companyId)
        {
            var token = _httpAccessor.HttpContext.Request.Cookies["timedoctor_accesstoken"];
            if (string.IsNullOrEmpty(token))
                return Json(new { Success = false, Result = "", Message = "Token is expired!!!" });

            var result = new
            {
                Projects = await GetProjectListByCompany(companyId),
                Users = await GetUserListByCompany(companyId),
            };
            return Json(new { Result = result, Success = true, Message = "" });
        }

        [HttpPost]
        public async Task<IActionResult> GetTimeDoctorData(WorkLogFilterDto input)
        {
            var token = _httpAccessor.HttpContext.Request.Cookies["timedoctor_accesstoken"];

            List<string> dateRanges = new List<string>();

            List<WorkLogByDates> data = new List<WorkLogByDates>();
            var day = 15;

            if (!string.IsNullOrEmpty(input.From) && !string.IsNullOrEmpty(input.To))
            {
                var newfDate = DateTime.Parse(input.From);
                var newtDate = DateTime.Parse(input.To);

                List<Tuple<DateTime, DateTime>> r = new List<Tuple<DateTime, DateTime>>();

                var startlop = true;
                while (startlop)
                {
                    var daysInMonth = DateTime.DaysInMonth(newfDate.Year, newfDate.Month);
                    DateTime endDat = DateTime.Now;

                    if (newfDate.Day <= 15)
                    {
                        endDat = new DateTime(newfDate.Year, newfDate.Month, 15, 23, 59, 59);
                    }
                    else if(newfDate.Day > 15 && daysInMonth == 31)
                    {
                        endDat = new DateTime(newfDate.Year, newfDate.Month, 31, 23, 59, 59);
                    }
                    else if(newfDate.Day > 15 && daysInMonth == 30)
                    {
                        endDat = new DateTime(newfDate.Year, newfDate.Month, 30, 23, 59, 59);
                    }

                    if (newtDate.Date == endDat.Date || newtDate.Date < endDat.Date)
                    {
                        r.Add(new Tuple<DateTime, DateTime>(newfDate, newtDate.AddDays(1).AddSeconds(-1)));
                        startlop = false;
                    }
                    else
                    {
                        r.Add(new Tuple<DateTime, DateTime>(newfDate, endDat));
                        newfDate = endDat.AddDays(1).Date;
                    }
                }

                for (int i = 0; i < r.Count; i++)
                {
                    var stDate = r[i].Item1;
                    var eDate = r[i].Item2;

                    input.From = stDate.ToString("yyyy-MM-ddTHH:mm:ssZ");
                    input.To = eDate.ToString("yyyy-MM-ddTHH:mm:ssZ");

                    data.Add(new WorkLogByDates
                    {
                        DateRange = stDate.ToString("MM/dd/yyyy") + " - " + eDate.ToString("MM/dd/yyyy"),
                        WorkLogs = await GetData(input, token)
                    });
                }


                var loopCount = Math.Ceiling((newtDate - newfDate).TotalDays / day);

                //for (int i = 0; i < loopCount; i++)
                //{


                //    if ((newtDate - newfDate).TotalDays > day)
                //    {
                //        var sDate = newfDate;
                //        var eDate = sDate.AddDays(day);

                //        input.From = newfDate.ToString("yyyy-MM-ddTHH:mm:ssZ");
                //        input.To = eDate.AddSeconds(-1).ToString("yyyy-MM-ddTHH:mm:ssZ");

                //        data.Add(new WorkLogByDates
                //        {
                //            DateRange = newfDate.ToString("MM/dd/yyyy") + " - " + eDate.AddSeconds(-1).ToString("MM/dd/yyyy"),
                //            WorkLogs = await GetData(input, token)
                //        });

                //        newfDate = eDate;
                //    }
                //    else if ((newtDate - newfDate).TotalDays <= day)
                //    {
                //        input.From = newfDate.ToString("yyyy-MM-ddTHH:mm:ssZ");
                //        input.To = newtDate.AddDays(1).AddSeconds(-1).ToString("yyyy-MM-ddTHH:mm:ssZ");

                //        data.Add(new WorkLogByDates
                //        {
                //            DateRange = newfDate.ToString("MM/dd/yyyy") + " - " + newtDate.AddDays(1).AddSeconds(-1).ToString("MM/dd/yyyy"),
                //            WorkLogs = await GetData(input, token)
                //        });
                //    }
                //}
            }

            data = data.Where(s => s.WorkLogs.Any()).ToList();

            return PartialView("~/Views/Shared/_WorkLogByUser.cshtml", data);
        }

        private async Task<List<WorkLogByUser>> GetData(WorkLogFilterDto input, string token)
        {
            var route = $"activity/worklog";
            route += "?company=" + input.CompanyId;

ClickuUpIntegration/Views/TimeDoctor/Worklog.cshtml
<style>
    div.ProjectOrder_0 {
    }

    div.ProjectOrder_1 {
        padding-left: 20px;
    }

    div.row.date-row {
        background: #ccc;
        padding: 10px 0px;
    }

    div.ProjectOrder_0, div.row.user-row {
        margin-top: 4px;
        font-weight: bold;
    }
    select.form-control[multiple], select.form-control[size] {
        height: calc(1.5em + 0.75rem + 2px) !important;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="RefreshToken">Refresh Token</a>
            <a class="navbar-brand" asp-area="" asp-controller="TimeDoctor" asp-action="Logout">Logout</a>
        </div>
    </nav>
</header>
<div class="container mt-5">
    <div class="row mb-2">
        <div class="col-md-6">
            <label>Select Company</label>
            <select class="form-control" name="companyId" id="companyId">
                <option value="">--Select Company--</option>
                @foreach (var company in ViewBag.Companies)
                {
                    <option value="@company.Id">@company.Name</option>
                }
            </select>
        </div>
        <div class="col-md-6">
            <label>Select Grouping</label>
            <select class="form-control" name="groupBy" id="groupBy">
                @foreach (var s in ViewBag.GroupByTypes)
                {
                    <option value="@s.Value">@s.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-6">
            <label>From Date:</label>
            <input type="date" class="form-control" placeholder="From Date" id="from" name="from" value="" />
        </div>
        <div class="col-md-6">
            <label>To Date:</label>
            <input type="date" class="form-control" placeholder="To Date" id="to" name="to" value="" />
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-6">
            <label>Select User</label>
            <select class="form-control" multiple name="userId" id="userId">
                <option value="">--Select User--</option>
            </select>
        </div>
        <div class="col-md-6">
            <label>Select Project</label>
            <select class="form-control" name="projectId" id="projectId">
                <option value="">--Select Project--</option>
            </select>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-12" style="margin-top:30px; text-align:center;">
            <button type="button" class="btn btn-primary" id="searchBtn">Search</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <span><b>Project Name</b></span>
        </div>
        <div class="col-md-5">
            <span style="padding-left:20px;"><b>Task Name</b></span>
        </div>
        <div class="col-md-2" style="display:none;" id="userNameShowHide">
            <span style="padding-left:20px;"><b>User Name</b></span>
        </div>
        <div class="col-md-2 text-right">
            <span><b>Total Hour</b></span>
        </div>
    </div>
    <div id="data-section">
    </div>
    @*@foreach (var prot in Model)
        {
            <div class="ProjectOrder_@prot.Order row">
                <div class="col-md-3">
                    <span>@prot.ProjectName</span>
                </div>
                <div class="col-md-7">
                    <span>@prot.TaskName</span>
                </div>
                <div class="col-md-2 text-right">
                    <span>@prot.TotalHour</span>
                </div>
            </div>
        }*@
</div>
@section scripts{
    <script>
        var users = [];
        $(document).on("click", "#searchBtn", function (e) {
            debugger;
            var fromDate = $("#from").val();
            var toDate = $("#to").val();
            var userId = $("#userId").val();
            var projectName = $("#projectId").val();
            var companyId = $("#companyId").val();

            if (userId === "") {
                var userIds = users.map(s => s.id);
                userId = userIds.join(",");
            }
            else {
                userId = userId.join(",");
            }

            var input = {
                from: fromDate,
                to: toDate,
                userId: userId,
                projectName: projectName,
                companyId: companyId,
                groupByType: $("#groupBy").val()
            };

            $.ajax({
                url: "/TimeDoctor/GetTimeDoctorData",
                type: 'POST',
                data: { input: input },
                cache: false,
                async: true,
            }).done(function (response) {
                var groupByType = $("#groupBy").val();
                if (groupByType === "0" || groupByType === "1") {
                    $("#userNameShowHide").hide();
                } else {
                    $("#userNameShowHide").show();
                }
                $("#data-section").html(response);
                $("select").selectpicker();
            }).fail(function (xhr) {
                alert('error : Either token expired or something went wrong' + xhr.status + ' - ' + xhr.statusText + ' - ' + xhr.responseText);
                console.log('error : ' + xhr.status + ' - ' + xhr.statusText + ' - ' + xhr.responseText);
            });

        });

        $(document).on("change", "#companyId", function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();

            if ($("#companyId").val() === "") {
                $("#projectId").empty();
                $("#projectId").append("<option value=''>--Select Project--</option>");

                $("#userId").empty();
                $("#userId").append("<option value=''>--Select User--</option>");
                return false;
            }

            $.getJSON("/TimeDoctor/GetDropdowns?companyId=" + $("#companyId").val(), "", function (response) {
                debugger;
                if (response.success) {
                    $("#userId").empty();
                    $("#userId").append("<option value=''>--Select User--</option>");
                    users = response.result.users;
                    $.each(response.result.users, function (i, v) {
                        $("#userId").append("<option value='" + v.id + "'>" + v.name + "</option>")
                    });

                    $("#projectId").empty();
                    $("#projectId").append("<option value=''>--Select Project--</option>");
                    $.each(response.result.projects, function (i, v) {
                        $("#projectId").append("<option value='" + v.name + "'>" + v.name + "</option>")
                    });
                    $("select").selectpicker();
                }
                else {
                    alert(response.message);
                }

            });
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

}